markdown: rdiscount
pygments: true
permalink: /:title
navigation:
  - heading: Smartmessages Docs
    topics:
    - text: Home
      url: /
  - heading: Using Smartmessages
    topics:
    - text: Getting started
      url: /using/
    - text: User guides
      url: /using/guides.html
    - text: Tutorials
      url: /using/tutorials.html
    - text: Video library
      url: /using/video.html
  - heading: Templates
    topics:
    - text: Overview
      url: /templates/
    - text: Syntax guide
      url: /templates/syntax.html
  - heading: Technical info
    topics:
    - text: Overview
      url: /tech/
    - text: SPF
      url: /tech/spf.html
    - text: DKIM
      url: /tech/dkim.html
  - heading: API
    topics:
    - text: Basics
      url: /api/
    - text: Clients
      url: /api/clients.html
    - text: Reference
      url: /api/reference.html
  - heading: Support
    topics:
    - text: Contact us
      url: mailto:info@smartmessages.net
